spring.application.name=gate
spring.datasource.url=jdbc:postgresql://localhost:5432/gate
spring.datasource.username=gate
spring.datasource.password=gate

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.session.timeout=10m
